'use client';
import { useMemo, useState } from 'react';
import type { PracticeRate, TrainingProfile, TrainingState, WeekDay } from '@/lib/training-types';
import { buildWeekCandidates } from '@/lib/training-planner';
import { dayLabels, kindLabel, numberOrNull } from './client';

type Props = { state: TrainingState; today: string; onChange: (state: TrainingState) => void; onSave: (state?: TrainingState) => Promise<boolean> };
function Days({ value, onChange }: { value: WeekDay[]; onChange: (value: WeekDay[]) => void }) {
  return <div className="training-choice-row">{dayLabels.map((label,index) => { const day = index + 1 as WeekDay; return <button key={day} type="button" aria-pressed={value.includes(day)} onClick={() => onChange(value.includes(day) ? value.filter(item => item !== day) : [...value,day])}>{label}</button>; })}</div>;
}
export function WeekPanel({ state, today, onChange, onSave }: Props) {
  const [weekOf, setWeekOf] = useState(today);
  const [profileOpen, setProfileOpen] = useState(state.profile.weeklyBudgetCny === null || state.profile.weeklyAvailableMinutes === null || !state.profile.availableDays.length);
  const profile = state.profile;
  const candidates = useMemo(() => buildWeekCandidates(profile, state.rates), [profile, state.rates]);
  const patchProfile = (value: Partial<TrainingProfile>) => onChange({ ...state, profile: { ...profile, ...value } });
  const patchRate = (id: string, value: Partial<PracticeRate>) => onChange({ ...state, rates: state.rates.map(rate => rate.id === id ? { ...rate, ...value } : rate) });
  function addRate() {
    onChange({ ...state, rates: [...state.rates, { id: crypto.randomUUID(), label: '新的训练地点', kind: 'gym', priceCny: null, billing: 'session', durationMinutes: 45, minimumMinutes: 45, courtIncluded: 'yes', courtFeeCny: null, courtBilling: 'hour', courtSplit: 1, travelMinutes: null, availableDays: [], notes: '' }] });
  }
  return <>
    <details className="training-panel training-details" open={profileOpen} onToggle={event => setProfileOpen(event.currentTarget.open)}><summary>个人条件与可用时间 <small>预算、场地、健身经验</small></summary><div className="training-grid">
      <label className="training-label">名字<input maxLength={100} value={profile.name} onChange={event => patchProfile({ name: event.target.value })}/></label><label className="training-label">惯用手<select value={profile.dominantHand} onChange={event => patchProfile({ dominantHand: event.target.value as TrainingProfile['dominantHand'] })}><option value="right">右手</option><option value="left">左手</option></select></label>
      <label className="training-label training-full">当前水平（自述）<input maxLength={200} value={profile.level} onChange={event => patchProfile({ level: event.target.value })}/><small>自述用于计划背景，系统不会据此自动判级。</small></label>
      <label className="training-label training-full">当前目标<textarea maxLength={4000} value={profile.goals} onChange={event => patchProfile({ goals: event.target.value })}/></label>
      <label className="training-label">每周训练预算（元）<input type="number" min="0" max="1000000" value={profile.weeklyBudgetCny ?? ''} onChange={event => patchProfile({ weeklyBudgetCny: numberOrNull(event.target.value) })}/></label>
      <label className="training-label">每周训练与往返可用分钟<input type="number" min="1" max="10080" step="1" value={profile.weeklyAvailableMinutes ?? ''} onChange={event => patchProfile({ weeklyAvailableMinutes: numberOrNull(event.target.value) })}/></label>
      <label className="training-label">每周最多练球次数（可留空）<input type="number" min="0" max="7" step="1" value={profile.maxCourtSessions ?? ''} onChange={event => patchProfile({ maxCourtSessions: numberOrNull(event.target.value) })}/></label>
      <fieldset className="training-full"><legend>个人可用星期</legend><Days value={profile.availableDays} onChange={availableDays => patchProfile({ availableDays })}/></fieldset>
      <label className="training-label training-full">健身经验<textarea maxLength={4000} value={profile.gymExperience} onChange={event => patchProfile({ gymExperience: event.target.value })} placeholder="做过哪些动作、是否熟悉器械与负重训练"/></label>
      <label className="training-label training-full">可用器械（逗号分隔）<input maxLength={2000} value={profile.equipment.join('、')} onChange={event => patchProfile({ equipment: event.target.value.split(/[,，、]/).map(value => value.trim()).filter(Boolean) })} placeholder="哑铃、弹力带、固定器械"/></label>
      <label className="training-label training-full">训练限制与教练要求<textarea maxLength={4000} value={profile.constraints} onChange={event => patchProfile({ constraints: event.target.value })}/></label>
    </div><div className="training-actions"><button className="training-button" onClick={() => onSave(state)}>保存个人条件</button></div></details>
    <section className="training-panel"><div className="training-section-head"><div><h2>价格与预约条件</h2><p>填写你的实际报价。会员单次边际费用为零时，请明确填 0；未知费用留空。</p></div><button className="training-secondary" onClick={addRate} disabled={state.rates.length >= 40}>添加地点</button></div><div className="training-rate-grid">{state.rates.map(rate => <article className="training-rate-card" key={rate.id}><div className="training-grid">
      <label className="training-label">名称<input maxLength={200} value={rate.label} onChange={event => patchRate(rate.id, { label: event.target.value })}/></label><label className="training-label">训练类型<select value={rate.kind} onChange={event => patchRate(rate.id, { kind: event.target.value as PracticeRate['kind'] })}>{Object.entries(kindLabel).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label>
      <label className="training-label">服务费用（元）<input type="number" min="0" value={rate.priceCny ?? ''} onChange={event => patchRate(rate.id, { priceCny: numberOrNull(event.target.value) })}/></label><label className="training-label">计价单位<select value={rate.billing} onChange={event => patchRate(rate.id, { billing: event.target.value as PracticeRate['billing'] })}><option value="session">每次预约</option><option value="hour">每小时</option></select></label>
      <label className="training-label">一次练习／每次报价的分钟<input type="number" min="1" max="1440" step="1" value={rate.durationMinutes} onChange={event => patchRate(rate.id, { durationMinutes: Number(event.target.value) })}/></label><label className="training-label">最低预约分钟<input type="number" min="1" max="1440" step="1" value={rate.minimumMinutes} onChange={event => patchRate(rate.id, { minimumMinutes: Number(event.target.value) })}/></label>
      <label className="training-label">是否含场地费<select value={rate.courtIncluded} onChange={event => patchRate(rate.id, { courtIncluded: event.target.value as PracticeRate['courtIncluded'] })}><option value="unknown">尚未确认</option><option value="yes">已包含／无额外费用</option><option value="no">另外支付</option></select></label><label className="training-label">往返分钟<input type="number" min="0" max="1440" step="1" value={rate.travelMinutes ?? ''} onChange={event => patchRate(rate.id, { travelMinutes: numberOrNull(event.target.value) })}/></label>
      {rate.courtIncluded === 'no' && <><label className="training-label">场地费用（元）<input type="number" min="0" value={rate.courtFeeCny ?? ''} onChange={event => patchRate(rate.id, { courtFeeCny: numberOrNull(event.target.value) })}/></label><label className="training-label">场地计价<select value={rate.courtBilling} onChange={event => patchRate(rate.id, { courtBilling: event.target.value as PracticeRate['courtBilling'] })}><option value="hour">每小时</option><option value="session">每次预约</option></select></label><label className="training-label">场地费分摊人数<input type="number" min="1" max="100" step="1" value={rate.courtSplit} onChange={event => patchRate(rate.id, { courtSplit: Number(event.target.value) })}/><small>只分摊场地费，私教／球机服务费用不再分摊。</small></label></>}
      <fieldset className="training-full"><legend>该服务可约星期（待确认时留空）</legend><Days value={rate.availableDays} onChange={availableDays => patchRate(rate.id, { availableDays })}/></fieldset>
      <label className="training-label training-full">备注<textarea maxLength={4000} value={rate.notes} onChange={event => patchRate(rate.id, { notes: event.target.value })}/></label>
    </div><button className="training-text-button" onClick={() => onChange({ ...state, rates: state.rates.filter(item => item.id !== rate.id) })}>移除此地点</button></article>)}</div></section>
    <section className="training-panel"><h2>比较每周安排</h2><p className="training-muted">先按预算、时间和可约星期筛选；训练次数是可调整候选。每天最多一次，健身安排在非练球日。尚未确认的信息会显示出来。</p><label className="training-label">计划起始日期<input type="date" value={weekOf} onChange={event => setWeekOf(event.target.value)}/></label><div className="training-plan-grid">{candidates.map(candidate => <article className="training-plan-card" key={candidate.id}><h3>{candidate.label}</h3><p>{candidate.rationale}</p><p><strong>{candidate.totalCostCny === null ? '费用待确认' : `¥${candidate.totalCostCny} / 周`}</strong><br/>{candidate.totalMinutes === null ? '含往返时间待确认' : `${candidate.totalMinutes} 分钟 / 周（含往返）`}</p><span className="training-badge" data-active={candidate.feasible === true}>{candidate.feasible === true ? '已填条件内可行' : candidate.feasible === false ? '暂不可行' : '待补充条件'}</span><ul>{candidate.visits.map((visit,index) => <li key={index}>{visit.day === null ? '日期待定' : dayLabels[visit.day - 1]} · {state.rates.find(rate => rate.id === visit.rateId)?.label} · {visit.minutes} 分钟</li>)}</ul>{candidate.warnings.map((warning,index) => <p className="training-muted" key={index}>{warning}</p>)}<button className="training-secondary" disabled={candidate.feasible !== true} onClick={() => onSave({ ...state, weekPlan: { ...candidate, weekOf, notes: '' } })}>采用这个安排</button></article>)}</div></section>
    {state.weekPlan && <section className="training-panel training-soft"><h2>已采用：{state.weekPlan.label}</h2><p>{state.weekPlan.weekOf} 起 · {state.weekPlan.visits.length} 次训练</p><ul>{state.weekPlan.visits.map((visit,index) => <li key={index}>{visit.day === null ? '日期待定' : dayLabels[visit.day - 1]} · {kindLabel[visit.kind]} · {visit.minutes} 分钟</li>)}</ul><label className="training-label">安排备注<textarea value={state.weekPlan.notes} maxLength={4000} onChange={event => onChange({ ...state, weekPlan: state.weekPlan ? { ...state.weekPlan, notes: event.target.value } : null })}/></label><button className="training-text-button" onClick={() => onChange({ ...state, weekPlan: null })}>清除当前安排</button></section>}
  </>;
}
